### ISSUE TITLE
Feature request: Add target filtering

### ISSUE THREAD

**Issue by figbux** [SoftSec-KAIST/Fuzzing-Survey#3]
Hello there,

Clarity of the sub categories i.e targets in the paper is missing in the website. Someone looking for XYZ fuzzer must click on each node to find what XYZ fuzzers are present. Target filtering (e.g via raido buttons) would be so helpful.

**Comment by sangkilc** [comment]
Good suggestion 👍 

We don't have enough resource to add such features at the moment, but we would love to accept PRs.

**Comment by sangkilc** [comment]
Handled by #9
