### ISSUE TITLE
Whitebox nodes are scattered around

### ISSUE THREAD

**Issue by figbux** [SoftSec-KAIST/Fuzzing-Survey#4]
Hello,
Apparently whitebox nodes don't tend to stay at right or somehow they cannot; a group of blackbox fuzzers occupied the rightmost territory.

**Comment by sangkilc** [comment]
This is not a bug. Since white-box fuzzer clusters are all connected with a black- or grey-box fuzzer, we don't see it at the righter territory.

**Comment by sangkilc** [comment]
I checked the code again, and I just found that the code for horizontal sorting part has been removed in the current version. I will fix the README description accordingly!
